### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by byxinyu** [LuPoYi/telegram-av-bot#1]
报错
root@digitalocean:~/telegram-av-bot# ruby main.rb
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- telegram/bot (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from main.rb:2:in `<main>'
root@digitalocean:~/telegram-av-bot#

**Comment by LuPoYi** [comment]
謝了，我忘了要先bundle install
